### ISSUE TITLE
Great! It would be nice to create such a plug-in for Sublime Text

### ISSUE THREAD

**Issue by lyza-shyrzai** [MilesCranmer/gso#21]
Great tool! It would be nice to create such a plugin for Sublime Text.

**Comment by MilesCranmer** [comment]
Thanks, @Liza-S!
You may be interested to know that GSO actually began as a sublime text plugin. (It actually had some nice multi-question/answer functionality!)

The remains of it are in the `sublime-text` branch—Google broke the API that I used at the time, and I switched to full-fledged vim, so I rewrote the plugin from scratch in its current form. It should be doable to adapt the code in the [`plugin/` directory](https://github.com/MilesCranmer/gso/tree/master/plugin) to work for Sublime, as I recall that you can write those in pure python. Let me know if you are interested in working on that.
