### ISSUE TITLE
This is awesome. 

### ISSUE THREAD

**Issue by satshabad-cr** [MilesCranmer/gso#25]
Oh and 
        title = result[u'pagemap'][u'qapage'][0][u'title']
        description = result[u'pagemap'][u'qapage'][0][u'description']

don't work anymore. Seems to work without those though.

**Comment by MilesCranmer** [comment]
Thanks for finding this, Satshabad. I'll take a look after Jan 23rd when I get back. Feel free to submit a pull request if you'd like too.
Cheers,
Miles

**Comment by satshabad-cr** [comment]
done. Enjoy your vacation!
